# Generated by Django 4.1.1 on 2022-09-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_alter_userinfo_state_alter_userinfo_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
