# Generated by Django 4.1.1 on 2022-09-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='user_image')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('rented_dates', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
