# Generated by Django 4.1.1 on 2022-09-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_rename_rented_dates_bikesmodel_is_rented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikesmodel',
            name='is_rented',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
